### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sakshi1706**
Change from http://ritchie.chem.ox.ac.uk/research_files/midirspectroscopy.htm
to
https://ritchie.web.ox.ac.uk/medicine as Page not found error. Current website there is no specific Infrared spectroscopy page but there is one page that gives information about infrared spectroscopy

### CODE REVIEW

**Review by phillipsp73 — COMMENTED** [review]
This is supposed to be a reference to an information source, if it is not available on any website, then we should remove any link to it.

**Comment by Sakshi1706** [comment]
Removed link from Mid-Infrared spectroscopy word

**Comment by phillipsp73** [comment]
You need to tidy up the markdown. Remove the brackets from "[Mid-Infrared Spectroscopy]".

**Comment by Sakshi1706** [comment]
Removed brackets

**Pull request merged**
